# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v9.0.0
_src_path: https://github.com/Tecnativa/doodba-copier-template.git
backup_dst: ""
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: en_US
odoo_listdb: false
odoo_listdb_staging: false
odoo_oci_image: ""
odoo_proxy: ""
odoo_version: 16.0
paths_with_crawlers:
  - /web/image/website
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "15"
project_author: Tecnativa
project_license: OEEL-1.0
project_name: odoo
smtp_default_from: ""
smtp_relay_host: ""
