version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "en_US"
      LIST_DB: "false"
      ODOO_BUS_PUBLIC_SAMESITE_WS: 1
      PGHOST: odoo-16-0-prod-db
    depends_on:
      - db
    networks:
      default:
    labels:
      doodba.domain.main: ""

  db:
    extends:
      file: common.yaml
      service: db
    environment:
      DB_HOST: odoo-16-0-prod-db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      default:
        aliases:
          - "odoo-16-0-prod-db"

networks:
  default:
    driver_opts:
      encrypted: 1

volumes:
  filestore:
  db:
